### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by AntJanus** [asteridux/paradux#2]
Create a logo for the lib

**Comment by theodorosploumis** [comment]
Hi, is this issue still active? I saw a logo on the project homepage.
I could help with this if you like. I am not a logo designer but I like creating logos and graphics for open source projects. Should I proceed?

Thanks in advanced!

**Comment by philals** [comment]
How about this? https://nargaque.files.wordpress.com/2010/05/pair_of_ducks.png?w=350&h=200&crop=1

**Comment by AntJanus** [comment]
whoops! I forgot to close this :) 

@theodorosploumis if you have a better logo in mind, by all means, I'd love to see it! :)

**Comment by theodorosploumis** [comment]
It's OK, close it. Thanks.
